//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

==== Question command
The question command serves to retrieve the information about the user question to retrieve his password.

===== Help message
[source,bash]
----
Usage: question [options]
  Options:
    --help 
    --list 
    --read 
       Syntax: --read {QUESTION-ID} {QUESTION-ID} [...]
    --delete 
       Syntax: --delete {QUESTION-ID} {QUESTION-ID} [...]
----

===== List option
Running the command with this option you will see the list of questions with their content.

[source]
--
$ ./syncopeadm.sh question --list
--

[source]
--

You are runnig: question --list 

  > SECURITY QUESTION ID: 1
    content: What's your mother's maiden name?

--

===== Read option
The option to read all the information of specified questions.

[source]
--
$ ./syncopeadm.sh question --read {QUESTION-ID} {QUESTION-ID} [...]
--

Unlike the list option, the read one shows only the questions passed as input.

===== Delete option
The option to delete the specified questions.

[source]
--
$ ./syncopeadm.sh question --delete {QUESTION-ID} {QUESTION-ID} [...]
--

The delete option, as can be imagined, tries to remove the specified questions. 
The output will be something like:
[source]
--
 - security question {QUESTION-ID} successfully deleted
--