//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

==== Connector command
The connector command serves to retrieve the information around the connector configuration in Apache Syncope.

===== Help message
[source,bash]
----
Usage: connector [options]
  Options:
    --help 
    --details 
    --list 
    --list-bundles 
    --list-configuration-properties
       Syntax: --list-configuration-properties {CONNECTOR-ID} {CONNECTOR-ID} [...]
    --read 
       Syntax: --read {CONNECTOR-ID} {CONNECTOR-ID} [...]
    --delete 
       Syntax: --delete {CONNECTOR-ID} {CONNECTOR-ID} [...]
----

===== Details option
This option shows a table with some details about connectors and bundles.

[source]
--
$ ./syncopeadm.sh connector --details
--

[source]
--

You are runnig: connector --details 

######################################
#                                    #
#         CONNECTORS DETAILS         #
#                                    #
######################################
#                          #         #
#          DETAIL          #  VALUE  #
#                          #         #
######################################
#                          #         #
#       Total number       #    9    #
#  With create capability  #    8    #
#  With delete capability  #    7    #
#  With search capability  #    8    #
#   With sync capability   #    4    #
#  With update capability  #    8    #
#      Bundles number      #    8    #
#                          #         #
######################################

--

Total number::
    number of created connectors;
With create capability::
    number of connectors configured with create capability;
With delete capability::
    number of connectors configured with delete capability;
With search capability::
    number of connectors configured with search capability;
With sync capability::
    number of connectors configured with sync capability;
With update capability::
    number of connectors configured with update capability;
Bundles number::
    number of bundles read by Syncope.

===== List option
Running the command with this option you will see the list of connectors with their configuration.

[source]
--
$ ./syncopeadm.sh connector --list
--

[source]
--

You are runnig: connector --list 

 > CONNECTOR ID: 108
    bundle name: net.tirasa.connid.bundles.db.scriptedsql
    connector name: net.tirasa.connid.bundles.db.scriptedsql.ScriptedSQLConnector
    display name: Scripted SQL
    location: connid://testconnectorserver@localhost:4554
    version: 2.2.3-SNAPSHOT
    timeout: 10
    CAPABILITIES:
       - CREATE
       - SEARCH
       - DELETE
       - UPDATE
       - SYNC
    CONFIGURATION:
       name: enableEmptyString
       values: [false]
       type: boolean
       display name: Enable writing empty string
       help message: <b>Enable writing empty string</b><br/>Select to enable support for writing an empty strings, instead of a NULL value, in character based columns defined as not-null in the table schema. This option does not influence the way strings are written for Oracle based tables. By default empty strings are written as a NULL value.
       order: 12
       default values: [false]
       confidential: false
       required: false
       overridable: false

       name: autoCommit
       values: [true]
       type: boolean
       display name: autoCommit
       help message: autoCommit
       order: 0
       default values: [true]
       confidential: false
       required: false
       overridable: false

       name: testScriptFileName
       values: [/home/massi/Lavoro/syncopeMaster/fit/core-reference/target/test-classes/scriptedsql/TestScript.groovy]
       type: java.lang.String
       display name: testScriptFileName
       help message: testScriptFileName
       order: 0
       default values: []
       confidential: false
       required: false
       overridable: true

--

The last snippet code shows a part of screen output. Basically you can read the configuration about every connectors
configured in Syncope.

===== List bundles option
Running the command with this option you will see the list of the bundles available in Syncope.

[source]
--
$ ./syncopeadm.sh connector --list-bundles
--

[source]
--

You are runnig: connector --list-bundles 

 > BUNDLE NAME: net.tirasa.connid.bundles.soap
    connector name: net.tirasa.connid.bundles.soap.WebServiceConnector
    display name: net.tirasa.connid.bundles.soap.WebServiceConnector
    location: file:/home/massi/Lavoro/syncopeMaster/fit/core-reference/target/bundles/
    version: 1.4.0-SNAPSHOT
 > BUNDLE NAME: net.tirasa.connid.bundles.db.scriptedsql
    connector name: net.tirasa.connid.bundles.db.scriptedsql.ScriptedSQLConnector
    display name: Scripted SQL Connector
    location: file:/home/massi/Lavoro/syncopeMaster/fit/core-reference/target/bundles/
    version: 2.2.3-SNAPSHOT
 > BUNDLE NAME: net.tirasa.connid.bundles.ldap
    connector name: net.tirasa.connid.bundles.ldap.LdapConnector
    display name: net.tirasa.connid.bundles.ldap.LdapConnector
    location: file:/home/massi/Lavoro/syncopeMaster/fit/core-reference/target/bundles/
    version: 1.5.0-SNAPSHOT
 > BUNDLE NAME: net.tirasa.connid.bundles.ad
    connector name: net.tirasa.connid.bundles.ad.ADConnector
    display name: net.tirasa.connid.bundles.ad.ADConnector
    location: file:/home/massi/Lavoro/syncopeMaster/fit/core-reference/target/bundles/
    version: 1.3.0-SNAPSHOT
 > BUNDLE NAME: net.tirasa.connid.bundles.db.table
    connector name: net.tirasa.connid.bundles.db.table.DatabaseTableConnector
    display name: Database Table Connector
    location: file:/home/massi/Lavoro/syncopeMaster/fit/core-reference/target/bundles/
    version: 2.2.3-SNAPSHOT
 > BUNDLE NAME: net.tirasa.connid.bundles.csvdir
    connector name: net.tirasa.connid.bundles.csvdir.CSVDirConnector
    display name: net.tirasa.connid.bundles.csvdir.CSVDirConnector
    location: file:/home/massi/Lavoro/syncopeMaster/fit/core-reference/target/bundles/
    version: 0.8.2
 > BUNDLE NAME: net.tirasa.connid.bundles.db.table
    connector name: net.tirasa.connid.bundles.db.table.DatabaseTableConnector
    display name: Database Table Connector
    location: connid://testconnectorserver@localhost:4554
    version: 2.2.3-SNAPSHOT
 > BUNDLE NAME: net.tirasa.connid.bundles.db.scriptedsql
    connector name: net.tirasa.connid.bundles.db.scriptedsql.ScriptedSQLConnector
    display name: Scripted SQL Connector
    location: connid://testconnectorserver@localhost:4554
    version: 2.2.3-SNAPSHOT

--

The most useful information are:

location::
    where the bundle is, it could be on the same server where Syncope is deployed or on a remote one linked by 
connid protocol;
version:
    the bundle version;

===== List configuration properties option
The option to read only the configuration of specified connectors.

[source]
--
$ ./syncopeadm.sh connector --list-configuration-properties {CONNECTOR-ID} {CONNECTOR-ID} [...]
--

The output is only the configuration of the connectors passed as input.

===== Read option
The option to read all the information of specified connectors.

[source]
--
$ ./syncopeadm.sh connector --read {CONNECTOR-ID} {CONNECTOR-ID} [...]
--

Unlike the list option, the read one shows only the connectors passed as input.

===== Delete option
The option to delete the specified connectors.

[source]
--
$ ./syncopeadm.sh connector --delete {CONNECTOR-ID} {CONNECTOR-ID} [...]
--

The delete option, as can be imagined, tries to remove the specified connectors. This operation works only if the 
connector isn't associated to a resource.
If the connector isn't associated to anything the output will be
[source]
--
 - Connector {CONNECTOR-ID} successfully deleted
--

other wise the output will be something like:
[source]
--
 - Error: AssociatedResources [ws-target-resource-nopropagation, ws-target-resource-nopropagation2]
--