//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

== Obtain Apache Syncope

There are several ways to obtain Apache Syncope: each of which has advantages or caveats for different types of users.

=== Standalone

The standalone distribution is the simplest way to start exploring Apache Syncope: it contains a fully working, in-memory
Tomcat-based environment that can be easily grabbed and put at work on any modern laptop, workstation or server. 

[CAUTION]
.Target Audience
First approach, especially with administration console and end-user; does not require technical skills. +
*Not meant for any production environment.*

Getting ready in a few easy steps:

. http://syncope.apache.org/downloads.html[download^] the standalone distribution
. unzip the distribution archive
. go into the created Apache Tomcat directory
. start Apache Tomcat
* GNU / Linux, Mac OS X
+
[source,bash]
----
$ chmod 755 ./bin/*.sh
$ ./bin/startup.sh
----
+
* Windows
+
[source,cmd]
----
> bin/startup.bat
----

[TIP]
Please refer to the http://tomcat.apache.org/tomcat-8.0-doc/[Apache Tomcat documentation^] for more advanced setup and 
instructions.

==== Components

The set of available components, including access URLs and credentials, is the same as reported for 
<<paths-and-components,embedded mode>>, with the exception of log files, available here under `$CATALINA_HOME/logs`.

[TIP]
.Internal Storage
====
By default, the standalone distribution is configured to use an in-memory database instance.
This means that every time Tomcat is shut down all changes that have been made are lost.

If you want instead to make your changes persistent, replace

[source,java]
jpa.url=jdbc:h2:mem:syncopedb;DB_CLOSE_DELAY=-1

with

[source,java]
jpa.url=jdbc:h2:~/syncopedb;DB_CLOSE_DELAY=-1

in `webapps/syncope/WEB-INF/classes/persistence.properties` from the Apache Tomcat directory.
This will create H2 database files in the home directory of the user running Apache Syncope.

Please refer to the http://www.h2database.com/[H2 documentation^] for more options.
====

include::commondocs/debpackages.adoc[]

include::commondocs/guiinstaller.adoc[]

==== Components

CAUTION: The following assumes that the Java EE container is reachable on host `host.domain` and port `port`. 

[cols="1,2"]
|===

| Complete REST API reference
| http://host.domain:port/syncope/index.html

| http://swagger.io/[Swagger^] UI
| http://host.domain:port/syncope/swagger/

| Administration console
| http://localhost:9080/syncope-console/ +
Credentials: `admin` / `password`

| End-user UI
| http://localhost:9080/syncope-enduser/

|===

include::commondocs/maven.adoc[]

==== Embedded Mode

Every Apache Syncope project has the ability to run a full-blown in-memory environment, particularly useful either when
evaluating the product and during the development phase of an IdM solution.

[WARNING]
====
Don't forget that this environment is completely in-memory: this means that every time Maven is stopped, all changes 
made are lost.
====

From the top-level directory of your project, execute:

[source,bash]
mvn -P all clean install

then, from the `enduser` subdirectory, execute:

[source,bash]
mvn -P embedded

===== Paths and Components

[cols="1,2"]
|===

| Log files
| Available under `core/target/log`, `console/target/log` and `enduser/target/log`

| ConnId bundles
| Available under `core/target/bundles`

| Complete REST API reference
| http://localhost:9080/syncope/index.html

| http://swagger.io/[Swagger^] UI
| http://localhost:9080/syncope/swagger/

| Administration console
| http://localhost:9080/syncope-console/ +
Credentials: `admin` / `password`

| End-user UI
| http://localhost:9080/syncope-enduser/

| Internal storage
| A SQL web interface is available at http://localhost:9080/syncope/db.jsp +
 +
 Choose configuration 'Generic H2 (Embedded)' +
 Insert `jdbc:h2:mem:syncopedb` as JDBC URL +
 Click 'Connect' button

| External resource: LDAP
| An http://directory.apache.org/apacheds/[Apache DS^] instance is available. +
You can configure any LDAP client (as http://jxplorer.org/[JXplorer^], for example) with the following information: +
 +
 host: `localhost` +
 port: `1389` +
 base DN: `o=isp` +
 bind DN: `uid=admin,ou=system` +
 bind password: `secret`

| External resource: SOAP
| An example SOAP server is available at http://localhost:9080/wssample/services +
 +
 You can check its internal data by visiting http://localhost:9080/wssample/exploredb.jsp

| External resource: database
| http://www.h2database.com/[H2^] TCP database is available. +
 +
 A SQL web interface is available at http://localhost:9082/ +
 +
 Choose configuration 'Generic H2 (Server)' +
 Insert `jdbc:h2:tcp://localhost:9092/mem:testdb` as JDBC URL +
 Set 'sa' as password +
 Click 'Connect' button

|===
