github:
  description: "Apache Syncope"
  homepage: https://syncope.apache.org/
  labels:
    - security
    - iam
    - idm
    - identity-management
    - identity-provisioning
    - identity-governance
    - iga
    - identity-lifecycle
    - user-workflow
    - user-requests
    - approval
    - scim
    - am
    - access-management
    - sso
    - websso
    - authentication
    - authorization
    - saml2
    - oauth2
    - openidconnect
    - ldap-authentication
    - identity-provider
    - duosecurity
    - u2f-server
    - api-management
    - api-gateway
    - proxies
    - proxy
    - enforce-policies
    - request-routing
    - service-mesh
    - microservices
    - reactor
  enabled_merge_buttons:
    # enable squash button:
    squash:  true
    # enable merge button:
    merge:   false
    # disable rebase button:
    rebase:  true

  notifications:
    commits:              commits@syncope.apache.org
    issues:               dev@syncope.apache.org
    pullrequests_status:  dev@syncope.apache.org
    pullrequests_comment: dev@syncope.apache.org
    jira_options:         link label worklog
