//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
==== Enable the Activiti Modeler

Due to licensing issues - see
https://issues.apache.org/jira/browse/SYNCOPE-439?focusedCommentId=13829896&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13829896[this comment^]
for more information - it is not possible to embed the
http://www.activiti.org/components.html#modeler[Activiti Modeler^], which provides a powerful graphical web editing
interface for Activiti BPM, into any Apache Syncope artifact; thus, some manual steps are required to enable it on a
working Apache Syncope deployment, for use with the admin console.

[WARNING]
This procedure requires Apache Maven since it is using a fake project to perform all of the required setup tasks.

First of all, generate a new Maven project as described in the
ifeval::["{backend}" == "html5"]
http://syncope.apache.org/docs/getting-started.html[Apache Syncope Getting Started Guide,]
endif::[]
ifeval::["{backend}" == "pdf"]
http://syncope.apache.org/docs/getting-started.pdf[Apache Syncope Getting Started Guide,]
endif::[]
then build via

....
mvn -P all clean install
....

At this point, copy the `console/target/activiti-modeler/` directory in the desired location of the host where the
admin console is deployed, then set the value of `activitiModelerDirectory` with this path in the `console.properties`
file.
