//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
==== Domains Management

<<domains>> are defined by three files in the <<properties-files-location,configuration directory>>; assuming
that the domain name is `Two`, such files are:

* `domains/TwoDomain.xml` - general configuration;
* `domains/Two.properties` - for <<dbms>> parameters;
* `domains/TwoContent.xml` - for content <<deal-with-internal-storage-export-import,initialization>>.

When adding a new domain to an existing deployment it is possible to copy, rename and edit the files available for
the `Master` domain, which is always present.

[CAUTION]
Adding a new domain requires re-deploying the <<core>> application and restarting the Java EE container.

Once a new domain is added, the admin credentials for such domain can be set via the admin console, CLI or
barely invoking the REST layer through http://curl.haxx.se/[curl^].
