//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
==== Executable

Apache Syncope can be run as standalone executable, without the need of a <<javaee-container>>; this goal is achieved
thanks to https://spring.io/projects/spring-boot[Spring Boot^] support.

Projects generated from Maven archetype feature a dedicated `executable` profile, which will re-package the
Core, Console and Enduser applications according to Spring Boot's
https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html[executable format^].

[TIP]
Spring Boot applications can also be
https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html[installed as system services^].

.Run Core application as executable under GNU / Linux
====
Assuming that the JDBC driver JAR file for the configured <<dbms>> is available under `/opt/syncope/lib`,
the Core application can be built and run as follows:

[source,bash]
----
$ mvn -P executable clean verify \
   -Dconf.directory=/opt/syncope/conf \
   -Dbundles.directory=/opt/syncope/bundles \
   -Dlog.directory=/opt/syncope/log
$ cp core/target/syncope.war /opt/syncope/lib
$ cp core/target/classes/*properties /opt/syncope/conf

$ export LOADER_PATH=/opt/syncope/conf,/opt/syncope/lib
$ java -jar /opt/syncope/lib/syncope.war
----
Further options can be passed to last command, according to Spring Boot
https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html[documentation^];
for example:

* `--spring.config.location=/path/to/file.properties` +
 to customize the location of the main Spring Boot's configuration file
* `--server.port=8080` +
 to change the default HTTP port
====
