//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
==== High-Availability

When deploying multiple Apache Syncope instances with a single database or database cluster, it is of
fundamental importance that the contained OpenJPA instances are correctly configured for
http://openjpa.apache.org/builds/2.4.2/apache-openjpa/docs/ref_guide_event.html[remote event notification^]. +
Such configuration, in fact, allows the OpenJPA data cache to remain synchronized when deployed in multiple JVMs, thus
enforcing data consistency across all Apache Syncope instances.

The default configuration in `domains.xml` is

[source,xml]
....
<entry key="openjpa.RemoteCommitProvider" value="sjvm"/>
....

which is suited for single JVM installations; with multiple instances, more options like as TCP or JMS are available;
see the OpenJPA documentation for reference.

[WARNING]
====
The OpenJPA documentation refers to direct configuration under `META-INF/persistence.xml`; for example:

[source,xml]
....
<property name="openjpa.RemoteCommitProvider" value="tcp(Addresses=10.0.1.10;10.0.1.11)"/>
....

while for use in `domains.xml`, this becomes:

[source,xml]
....
<entry key="openjpa.RemoteCommitProvider" value="tcp(Addresses=10.0.1.10;10.0.1.11)"/>
....
====
