//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
==== Identity Recertification

Recertification is the process to review all the identities and access within one organization. This is a tipical countermeasure against the  __privilege creep__, that is the rentention of accounts during time even when the user change his role, or even his job. Ths good practice is recomendded and often required by international or organizational standards.

Tipically every "object" within one IDM system needs to be periodically re-certified:

* Identities: Is the user still valid for the organization?
* Accounts: Is thie user still using this account?
* Group Membership/Entitlements: Does the user require this functionality?

One simple scheduled job to implement Identity Recertification is provided. The class name is: __org.apache.syncope.core.provisioning.java.job.IdentityRecertification__ .
It can be used as base to implement more complex recertification processes.
It go through all the users and check if they have been recertified the past __identity.recertification.day.interval__ days. This is a global Parameter that can be set using Syncope Console or REST webservices.
The recertificaton task implemented by default set two attributes for each users:
- lastRertificator: the name of the user that re-certified the user
- lastRecertiication: the date when the re-certification is performed
This task is implement by the class: __org.apache.syncope.core.workflow.activiti.task.Recertify__
The certificator can be defined modifying the task: "Create Recertification". Actviti is very flexible, and allows to define approver user, groups, or even to use expression language to define approvers from attributes from the user, for example the user manager.

Example 1: Certifier users are members of managingDirector group:
=====================================================================
    <userTask id="createApproval" name="Create approval"
              activiti:candidateGroups="managingDirector" 
              activiti:formKey="createApproval">
=====================================================================

Example 2: Certifier user is the user manager defined in the user attribute: __lastRecertificator__
=====================================================================
    < userTask id = "createApproval" name = "Create Recertification"
               activiti:candidateGroups="${user.lastRecertificator}" 
               activiti:formKey="createApproval">
=====================================================================
