//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
==== Set admin credentials

[WARNING]
The procedure below affects only the `Master` <<domains,domain>>; for other domains check <<domains-management,above>>.

The default password for the `admin` user is `password`.

The credentials are defined in the `security.properties` file; text encoding must be set to UTF-8:

* `adminUser` - administrator username
* `adminPassword` - SHA1 hash evaluation of cleartext password (represented as a sequence of 40 hexadecimal digits)
* `adminPasswordAlgorithm` - algorithm to be used for hash evaluation (default value: SHA1)

For GNU / Linux and Mac OS X, the SHA1 password can be obtained via the `sha1sum` command-line tool of
http://www.gnu.org/software/coreutils/[GNU Core Utilities^]:

[source,bash]
....
echo -n "new_password" | sha1sum
....
For MS Windows, some options are available:

* http://support.microsoft.com/kb/841290[MS File Checksum Integrity Verifier^] +
install, save your password to a file (e.g. `password.txt` without EOL) and issue at command line: +
[source,bash]
....
fciv.exe -sha1 password.txt
....
* http://gnuwin32.sourceforge.net/[GnuWin32^] port of GNU utilities for MS Windows
* http://www.cygwin.com/[Cygwin^] Unix-like environment and command-line interface for Microsoft Windows (featuring
http://www.gnu.org/software/coreutils/[GNU Core Utilities^])
