//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
=== Maven Project

This is the *preferred method* for working with Apache Syncope, giving access to the whole set of customization
and extension capabilities.

[CAUTION]
.Target Audience
Provides access to the full capabilities of Apache Syncope, and almost all extensions that are possible. +
*Requires Apache Maven (and potentially https://en.wikipedia.org/wiki/DevOps[DevOps^]) skills.*

==== Prerequisites

 . http://maven.apache.org/[Apache Maven^] (version 3.0.3 or higher) installed
 . Some basic knowledge about Maven
 . Some basic knowledge about http://maven.apache.org/guides/introduction/introduction-to-archetypes.html[Maven archetypes^].

==== Create project

Maven archetypes are templates of projects. Maven can generate a new project from such a template. 
In the folder in which the new project folder should be created, type the command shown below. 
On Windows, run the command on a single line and leave out the line continuation characters ('\').

ifeval::["{snapshotOrRelease}" == "release"]

[subs="verbatim,attributes"]
----
mvn archetype:generate \
    -DarchetypeGroupId=org.apache.syncope \
    -DarchetypeArtifactId=syncope-archetype \
    -DarchetypeRepository=http://repo1.maven.org/maven2 \
    -DarchetypeVersion={docVersion}
----

endif::[]

ifeval::["{snapshotOrRelease}" == "snapshot"]

[subs="verbatim,attributes"]
----
mvn archetype:generate \
    -DarchetypeGroupId=org.apache.syncope \
    -DarchetypeArtifactId=syncope-archetype \
    -DarchetypeRepository=http://repository.apache.org/content/repositories/snapshots \
    -DarchetypeVersion={docVersion}
----

[WARNING]
====
Once the Maven project is generated, add the following right before `</project>` in the root `pom.xml` of the 
generated project:

[source,xml]
----
<repositories>
  <repository>
    <id>ASF</id>
    <url>https://repository.apache.org/content/repositories/snapshots/</url>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
----
====

endif::[]

The archetype is configured with default values for all required properties; if you want to customize any of these 
property values, type 'n' when prompted for confirmation.

You will be asked for:

groupId::
    something like 'com.mycompany'
artifactId::
    something like 'myproject'
version number::
    You can use the default; it is good practice to have 'SNAPSHOT' in the version number during development and the 
maven release plugin makes use of that string. But ensure to comply with the desired numbering scheme for your project.
package name::
    The java package name. A folder structure according to this name will be generated automatically; by default, equal 
to the groupId.
secretKey::
    Provide any pseudo-random string here that will be used in the generated project for AES ciphering.
anonymousKey:: 
    Provide any pseudo-random string here that will be used as an authentication key for anonymous requests.

Maven will create a project for you (in a newly created directory named after the value of the `artifactId` property 
specified above) containing three modules: `common`, `core` and `console`.

You are now able to perform the first build via

[source,bash]
mvn clean verify

After downloading all of the needed dependencies, two WAR files will be produced:

. `core/target/syncope.war`
. `console/target/syncope-console.war`

If no failures are encountered, your basic Apache Syncope project is now ready to go.

[NOTE]
You should consider reading the _Apache Syncope Reference Guide_ to understand how to configure, extend, customize 
and deploy your new Apache Syncope project.