//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
=== High-Availability

==== Core HA

When deploying multiple Syncope <<core>> instances with a single database or database cluster, it is of
fundamental importance that the https://docs.hibernate.org/orm/7.4/userguide/html_single/#caching[second-level cache^]
is correctly configured for Hibernate ORM.
Such configuration, in fact, allows the Hibernate ORM cache to remain synchronized across multiple JVMs, thus
enforcing data consistency across all Syncope Core instances.

The supported https://github.com/jsr107/jsr107spec[JCache^] provider is configured according to the implementation found
in the classpath.

[WARNING]
Ensure to define only one of the following providers to avoid conflicts.

[core-ha-caffeine]
===== Caffeine

By default, the following dependency is set in `core/pom.xml`.

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.apache.syncope.core.cache</groupId>
  <artifactId>syncope-core-cache-caffeine</artifactId> 
  <version>${syncope.version}</version>
</dependency>
----

[WARNING]
https://github.com/ben-manes/caffeine[Caffeine^] does support only single JVM installations.

[core-ha-ehcache]
===== Ehcache

Set the following dependency is in `core/pom.xml` to enable https://www.ehcache.org/documentation/3.11/107.html[Ehcache^]:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.apache.syncope.core.cache</groupId>
  <artifactId>syncope-core-cache-caffeine</artifactId> 
  <version>${syncope.version}</version>
</dependency>
----

[TIP]
Adding `ehcache.xml` in the classpath will allow to fine-tune Ehcache's https://www.ehcache.org/documentation/3.11/xml.html[configuration^].

[core-ha-hazelcast]
===== Hazelcast

Set the following dependency is in `core/pom.xml` to enable https://docs.hazelcast.com/hazelcast/5.7/jcache/overview[Hazelcast^]:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.apache.syncope.core.cache</groupId>
  <artifactId>syncope-core-cache-hazelcast</artifactId> 
  <version>${syncope.version}</version>
</dependency>
----

[TIP]
Adding `hazelcast.xml` in the classpath will allow to fine-tune Hazelcast's https://docs.hazelcast.com/hazelcast/5.7/configuration/understanding-configuration[configuration^].

[core-ha-infinispan]
===== Infinispan

Set the following dependency is in `core/pom.xml` to enable https://infinispan.org/docs/stable/titles/embedding/embedding.html[Infinispan^]:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.apache.syncope.core.cache</groupId>
  <artifactId>syncope-core-cache-infinispan</artifactId> 
  <version>${syncope.version}</version>
</dependency>
----

==== WA HA

When multiple Syncope <<web-access>> instances are needed to support authentication and authorization requirements, 
a distributed https://apereo.github.io/cas/8.0.x/ticketing/Configuring-Ticketing-Components.html#ticket-registry[Ticket Registry^]
is required, such has the ones based on
https://apereo.github.io/cas/8.0.x/ticketing/Hazelcast-Ticket-Registry.html[Hazelcast^]
or https://apereo.github.io/cas/8.0.x/ticketing/Ignite-Ticket-Registry.html[Apache Ignite^].
