//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
=== High-Availability

==== Core HA

When deploying multiple Syncope <<core>> instances with a single database or database cluster, it is of
fundamental importance that the https://docs.hibernate.org/orm/7.2/userguide/html_single/#caching[second-level cache^]
is correctly configured for Hibernate ORM.
Such configuration, in fact, allows the Hibernate ORM cache to remain synchronized across multiple JVMs, thus
enforcing data consistency across all Syncope Core instances.

The default configuration in `core.properties` is

[source]
....
persistence.cacheProvider=com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
....

which is suited for single JVM installations; with multiple instances, more options are available depending on the
configured https://github.com/jsr107/jsr107spec[JCache^] implementation, such as, for example,
https://docs.hazelcast.com/hazelcast/5.6/jcache/overview[Hazelcast^],
https://www.ehcache.org/documentation/3.0/107.html[Ehcache],
https://infinispan.org/docs/stable/titles/hibernate/hibernate.html[Infinispan^] or
https://ignite.apache.org/[Apache Ignite^].

Additional, implementation-specific configuration files can be set up via `persistence.cacheURI`.

==== WA HA

When multiple Syncope <<web-access>> instances are needed to support authentication and authorization requirements, 
a distributed https://apereo.github.io/cas/7.3.x/ticketing/Configuring-Ticketing-Components.html#ticket-registry[Ticket Registry^]
is required, such has the ones based on
https://apereo.github.io/cas/7.3.x/ticketing/Hazelcast-Ticket-Registry.html[Hazelcast^]
or https://apereo.github.io/cas/7.3.x/ticketing/Ignite-Ticket-Registry.html[Apache Ignite^].
