//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
===== Configuration

The configuration pages allow the designated administrators to customize the given deployment to fit the needs of the
organization.

[[console-configuration-audit]]
Audit::

Controls the configuration of the <<audit,auditing>> features.

[[console-configuration-implementations]]
Implementations::

Allows the administrators to manage <<implementations,implementations>>.

[[console-configuration-logs]]
Logs::

The logging levels available can be dynamically adjusted; for example, the admin can set it
to display only the errors of `io.swagger`, in which case the warning and information logs will not be reported.

[[console-configuration-notifications]]
Notifications::

Gives access to the <<notifications,notification>> management. +
This page also allows the administrators to create and edit <<notification-templates,notification templates>>.

[[console-configuration-policies]]
Policies::

Allows the administrators to manage all available type of <<policies,policies>>.

[[console-configuration-security]]
Security::

Displays and provides editing functionality for the security aspects, including <<roles,roles>>,
<<delegation,delegations>> and <<security-questions,security questions>>.

[[console-configuration-types]]
Types::

Entry point for <<type-management,type management>>.
