//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
===== Configuration

The configuration pages allow the designated administators to customize the given deployment to fit the needs of the
organization.

[[console-configuration-audit]]
Audit::

Controls the configuration of the <<audit,auditing>> features.

[[console-configuration-logs]]
Logs::

The logging levels available can be dynamically adjusted; for example, the admin can set it
to display only the errors of `io.swagger`, in which case the warning and information logs will not be reported.

[[console-configuration-notifications]]
Notifications::

Gives access to the <<notifications,notification>> management. +
This page also allows the administators to create and edit <<notification-templates,notification templates>>.

[[console-configuration-parameters]]
Parameters::

Presents the administrators with the list of defined <<configuration-parameters,configuration parameters>> used in the
given deployment such as `token.expireTime` and `password.cipher.algorithm`.
These can be edited to further customize the deployment. +
New parameters can also be added, for use with custom code. 

[[console-configuration-policies]]
Policies::

Allows the administrators to manage <<policies-account,account>>, <<policies-password,password>> and
<<policies-pull,pull>> policies.

[[console-configuration-roles]]
Roles::

Displays and provides editing functionality for <<roles,roles>>.

[[console-configuration-security-questions]]
Security Questions::

The administrators can use this page to define a set of security questions which the users can choose from when
managing their own profile, to allow them to recover their account in case of a <<password-reset,forgotten password>>.
