//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
=== Upgrade from 2.1

The distance between earlier releases and Syncope 3.0 Maggiore is relevant under different aspects: architecture,
technology, project organization and naturally internal data representation.

For this reason [.underline]#there is no practical way to migrate an old project# to Syncope 3.0.

It is possible, however, to setup a new Syncope 3.0 project, replicate configurations and finally migrate the existing
data. Here is the outlined approach:

. create a new Maven project based on Syncope 3.0
. update code customization and extensions made from your previous Syncope project to the new classes and interfaces
provided by Syncope 3.0
. with both projects up and running:
    .. download relevant configurations - especially connectors and resources - via REST from your previous Syncope
project
    .. upload via REST to the new Syncope 3.0 project
    .. configure a new REST resource in the new Syncope 3.0 project to pull users, groups and any objects from your
previous Syncope project
