//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
==== Connectors
Syncope uses entities like connectors bundles, connector instances and external resources to synchronize user accounts 
with and propagate to external systems. This paragraph clarifies what the responsibility and scope of each of these entities are.

===== Connector bundle
Connector bundles are the components that are able to connect to classes of systems when configured correctly and 
told to do so. They are not bound to Syncope specifically, as they are part of the separate framework 
http://connid.tirasa.net/[ConnId], but  they can be plugged into a deployed Syncope system.

===== Connector instance
Connectors instances are instance of connector bundles, obtained by assigning values to configuration properties
defined in bundles.
For instance, there is only a single "DatabaseTable connector" (the bundle) that can be instantiated many times, for 
example if there is need to connect to two different databases.