//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
==== Synchronization
Basically, the synchronization is the mechanism used by Apache Syncope to acquire user/group data from external resources.
Synchronization can be "full" (full reconciliation) or "incremental".
In the former case, each sync task execution will take over just of changes from the previous execution 
(if exists and connector permits incremental sync).
In the latter case, each sync task execution will take over of the entire set of data managed by the external resource.

===== From an external resource to Syncope
All the entity (user/group) data involved by a synchronization are retrieved from an external resource and processed 
internally by Syncope itself.
A retrieved entity can be:

. a matching entity, if a corresponding local/internal entity has been found;
. or an unmatching entity, otherwise.

By default, Syncope will create locally all the unmatching entities (without linking entities and resources) and will 
update all the matching ones.
By the way, a different behaviour can be configured working with matching/unmatching rules.

===== Matching and Unmatching rules
Unmatching (corresponding user not found on Syncope):

* IGNORE / UNLINK (do not perform any action);
* ASSIGN (create entity linking the resource);
* PROVISION (create entity without linking the resource).

Matching (corresponding users found on Syncope):

* IGNORE (do not perform any action);
* UPDATE (update matching entity);
* DEPROVISION (delete resource entity);
* UNASSIGN (unlink resource and delete resource entity) ;
* UNLINK (just unlink resource without performing any (de-)provisioning operation);
* LINK (just link resource without performing any (de-)provisioning operation).