//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
=== Digital identity
To briefly introduce what the digital identity means, we report what the https://en.wikipedia.org/wiki/Digital_identity[Wikipedia]
says about it

****
A digital identity is information used by computer systems to represent an external agent. That agent may be a person, 
organisation, or device. The information in digital identities is used by computers to make decisions about how to 
interact with external agents. It allows a computer to answer two basic questions:

With which external agent is it interacting?
Has it interacted with an external agent in the past?
The information contained in a digital identity allows these questions to be answered without the involvement of human 
operators. Digital identities allow our access to computers and the services they provide to be automated, and make it 
possible for computers to mediate relationships.

The term "digital identity" has also come to denote aspects of civil and personal identity that have resulted from the 
widespread use of identity information to represent people in computer systems.

Digital identity is now often used in ways that require data about persons stored in computer systems to be linked to 
their civil, or national, identities. Furthermore, the use of digital identities is now so widespread that many 
discussions refer to "digital identity" as the entire collection of information generated by a person’s online activity. 
Especially where that information is publicly available, and can be used by others to discover that person's civil identity. 
In this wider sense, a digital identity is a version, or facet, of a person's social, identity. This may also referred 
to as an online identity.
****
