//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
=== A bit of history
Syncope, officially, borns at the end of April 2010 with the first https://code.google.com/p/syncope/source/detail?r=1[commit]
on the GoogleCode repository.
Syncope development started from a group of IdM experts and Open Source enthusiasts; it starts to be an Open Source project,
so after two years the developers tried to donate the code to the Apache Software Foundation and, precisely in February
2012, Syncope became an ASF project; of course starting its journey from the incubator state.

Now, after three years as ASF project, the community counts 16 developers (from different countries) and hundreds of ML
members.

From the project's point of view, there isn't a website to find a complete list of project reference, but reading
the user mailing list and this one[http://syncope.tirasa.net/success-stories.html], you can say that several companies
have chosen Syncope as their own identity manager system.
