//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
=== Metrics

Monitoring performance to ensure reliability and efficiency can be achieved by leveraging 
https://docs.spring.io/spring-boot/4.0/reference/actuator/metrics.html[Spring Boot's metrics^].

[[metrics-core]]
==== Core

This can be enabled by adding the following dependency to `core/pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.apache.syncope.core</groupId>
  <artifactId>syncope-core-metrics-starter</artifactId>
  <version>${syncope.version}</version>
</dependency>
----

Additional dependencies might be required, depending on the
https://docs.spring.io/spring-boot/4.0/reference/actuator/metrics.html#actuator.metrics.export[actual monitoring system in use^].

[[metrics-wa]]
==== WA

This can be enabled by adding the following dependency to `wa/pom.xml`:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.apereo.cas</groupId>
  <artifactId>cas-server-support-metrics</artifactId>
  <version>${cas.version}</version>
</dependency>
----

For further options and configuration, refer to https://apereo.github.io/cas/7.3.x/monitoring/Configuring-Metrics.html[CAS documentation^].
