//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

==== Entitlement command
The entitlement command serves to retrieve the information about the entitlments.

===== Help message
[source,bash]
----
Usage: entitlement [options]
  Options:
    --help 
    --list
    --list-role
       Syntax: --list-role {ENTITLEMENT-NAME}
    --read-by-username
       Syntax: --read-by-username {USERNAME}
    --read-by-userid
       Syntax: --read-by-userid {USER-ID}
    --search-by-role
       Syntax: --search-by-role {ROLE-ID}
----

===== List option
Running the command with this option you will see the list of the entitlements.

[source]
--
$ ./syncopeadm.sh entitlement --list
--

[source]
--

You are runnig: entitlement --list 

- CONNECTOR_READ
- NOTIFICATION_DELETE
- ANYTYPE_UPDATE
- RELATIONSHIPTYPE_UPDATE
- SCHEMA_CREATE
[...]

--

===== List role option
Running the command with this option you will see the list of the roles with a certain entitlement.

[source]
--
$ ./syncopeadm.sh entitlement --list
--

[source]
--

You are runnig: entitlement --list-role PRINTER_DELETE 

 > ROLE ID: Search for realm evenTwo
    REALMS: 
       - /even/two

 > ROLE ID: User manager
    REALMS: 
       - /

 > ROLE ID: User reviewer
    REALMS: 
       - /odd
       - /even

 > ROLE ID: Other
    REALMS: 
       - /odd

--

===== Read by username option
The option to read the entitlements of the username passed as input.

[source]
--
$ ./syncopeadm.sh entitlement --read-by-username {USERNAME}
--
[source]
--
You are runnig: entitlement --read-by-username rossini 

- GROUP_READ
- SCHEMA_READ
- WORKFLOW_FORM_CLAIM
--

===== Read by userid option
The option to read the entitlements of the userid passed as input.

[source]
--
$ ./syncopeadm.sh entitlement --read-by-userid {USER-ID}
--
[source]
--
You are runnig: entitlement --read-by-userid 5 

- USER_READ
- USER_SEARCH
--

===== Search by role option
The option to read the entitlements of a certain role.

[source]
--
$ ./syncopeadm.sh entitlement --search-by-role {ROLE-ID}
--

[source]
--
You are runnig: entitlement --search-by-role Other 

- SCHEMA_READ
- GROUP_READ
- WORKFLOW_FORM_CLAIM
--