//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

==== Introduction
A brief introduction about this document and the examples you will find reading it.

Once you have downloaded and unzipped the zip file containing the scripts, you will find a lib directory and 
two script files, a .bat and a .sh one, called _syncopeadm_. You will use one of these files, depending on your operating system.

[NOTE]
Every example described in this document is executed on a linux machine with a _debug environment_.

[NOTE]
Wikipedia suggests that a https://en.wikipedia.org/wiki/Command-line_interface[command line interface] (CLI) 
is a means of interacting with a computer program, where the user (or client) issues commands to the program 
in the form of successive lines of text (command lines). In our case the CLI tool is the way to call, more or less, 
every Syncope core command through a shell.
