//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

==== Policy command
The policy command retrieves information about the policies for each type.

===== Help message
[source,bash]
----
Usage: policy [options]
  Options:
    --help 
    --details 
    --list 
       Syntax: --list-policy {POLICY-TYPE} 
          Policy type: ACCOUNT / PASSWORD / SYNC / PUSH
    --read 
       Syntax: --read {POLICY-ID} {POLICY-ID} [...]
    --delete 
       Syntax: --delete {POLICY-ID} {POLICY-ID} [...]
----

===== Details option
This option shows a table with the amount of policies for each type.

[source]
--
$ ./syncopeadm.sh policy --details
--

[source]
--

You are running: policy --details 

#################################
#                               #
#       POLICIES DETAILS        #
#                               #
#################################
#                     #         #
#       DETAIL        #  VALUE  #
#                     #         #
#################################
#                     #         #
#    total number     #    9    #
#  account policies   #    2    #
#  password policies  #    3    #
#    sync policies    #    4    #
#    push policies    #    0    #
#                     #         #
#################################

--

===== List option
Running the command with this option you will see the list of the policies.

[source]
--
$ ./syncopeadm.sh Usage: policy --list {POLICY-TYPE}
   Policy type: ACCOUNT / PASSWORD / SYNC / PUSH
--

[source]
--

You are running: policy --list SYNC 

 > KEY: 1
    type: SYNC
    description: a sync policy
    resources : []
    realms : []

 > KEY: 3
    type: SYNC
    description: sync policy 2
    resources : [resource-csv]
    realms : []
    conflict resolution action: ALL
    correlation rule : {USER=["username","firstname"]}

 > KEY: 7
    type: SYNC
    description: sync policy 1
    resources : []
    realms : []
    conflict resolution action: IGNORE
    correlation rule : {}

 > KEY: 9
    type: SYNC
    description: sync policy for java rule
    resources : [ws-target-resource-2]
    realms : []
    conflict resolution action: IGNORE
    correlation rule : {}

--

===== Read option
The option to read all the information of a specified policy.

[source]
--
$ ./syncopeadm.sh policy --read {POLICY-ID} {POLICY-ID} [...]
--

Unlike the list option, the read option shows only the policy passed as input.
[source]
--
You are running: policy --read 6 

 > KEY: 6
    type: ACCOUNT
    description: sample account policy
    resources : []
    realms : [/odd]
    max authentication attempts : 3
    propagation suspension : false
    RULES : 
       > class : [org.apache.syncope.common.lib.policy.DefaultAccountRuleConf@708a538f[
  maxLength=0
  minLength=4
  pattern=<null>
  allUpperCase=false
  allLowerCase=false
  wordsNotPermitted=[]
  schemasNotPermitted=[]
  prefixesNotPermitted=[notpermitted1, notpermitted2]
  suffixesNotPermitted=[]
  name=org.apache.syncope.common.lib.policy.DefaultAccountRuleConf
]]
--

===== Delete option
The option to delete a specified policy.

[source]
--
$ ./syncopeadm.sh policy --delete {POLICY-ID} {POLICY-ID} [...]
--

The delete option, as can be imagined, tries to remove a specified policy. 
The output will be something like:
[source]
--
 - Policy {POLICY-ID} successfully deleted
--
