//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
[[password-reset]]
==== Password Reset

When users lost their password, a feature is available to help gaining back access to Apache Syncope: password reset.

The process can be outlined as follows:

. user asks for password reset, typically via end-user
. user is asked to provide an answer to the security question that was selected during self-registration or self-update
. if the expected answer is provided, a unique token with time-constrained validity is internally generated and an
e-mail is sent to the configured address for the user with a link - again, typically to the
end-user - containing such token value
. user clicks on the received link and provides new password value, typically via end-user
. user receives confirmation via e-mail

[WARNING]
====
The outlined procedure requires a working <<e-mail-configuration,e-mail configuration>>.

In particular:

* the first e-mail is generated from the `requestPasswordReset` <<notification-templates, notification template>>:
hence, the token-based access link to the end-user is managed there;
* the second e-mail is generated from the `confirmPasswordReset` <<notification-templates, notification template>>.
====

[TIP]
====
The process above requires the availability of <<security-questions,security questions>> that
users can pick up and provide answers for.

The usage of security questions can be however disabled by setting the `passwordReset.securityQuestion` value - see
<<configuration-parameters, below>> for details.
====

[[password-reset-no-security-answer]]
[WARNING]
====
Once provided via Enduser Application, the answers to security questions are *never* reported, neither via REST or Admin UI to
administrators, nor to end-users via Enduser Application.

This to avoid any information disclosure which can potentially lead attackers to reset other users' passwords.
====

[NOTE]
In addition to the password reset feature, administrators can set a flag on a given user so that he / she is forced to
update their password value at next login.

===== Password Reset Request Throttling
This functionality can throttle repeated password reset requests to reduce the effectiveness of automated guessing
against security answers and to limit password reset email abuse.

This protection is configured in `core.properties` via the following properties:

[cols="1,3"]
|===
|Property |Description
|`security.passwordResetThrottle.enabled`
|Whether password reset request throttling is enabled. When set to `false`, password reset requests are not
rate-limited by this mechanism.
|`security.passwordResetThrottle.maxAttempts`
|Maximum number of password reset requests allowed for the same Domain, username and client address within the
configured time window.
|`security.passwordResetThrottle.windowSeconds`
|Time window, in seconds, used to count password reset requests.
|`security.passwordResetThrottle.lockSeconds`
|Time, in seconds, during which further password reset requests for the same Domain, username and client address are
rejected after the maximum number of requests has been exceeded.
|===

A possible configuration is:
[source,properties]
----
security.passwordResetThrottle.enabled=true
security.passwordResetThrottle.maxAttempts=5
security.passwordResetThrottle.windowSeconds=300
security.passwordResetThrottle.lockSeconds=300
----

When enabled, the core tracks password reset requests for each combination of Domain, username and client address.
The client address is obtained from the servlet request remote address.

Once more than `security.passwordResetThrottle.maxAttempts` requests are received within
`security.passwordResetThrottle.windowSeconds`, further password reset requests for the same combination are rejected
for `security.passwordResetThrottle.lockSeconds`.

During the lock interval, the requester receives an HTTP `429 Too Many Requests` response with a `Retry-After` header.

[NOTE]
The client address is part of the throttling key to avoid allowing a client that knows a username or email address to
globally block password reset for that account from other client addresses.
