//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
==== Propagation
The propagation is the mechanism to extend provisioning operations on external resources.
The propagation layer implements remote creation, maintenance, activation and deactivation of user and role objects 
and their attributes.
A propagation towards a specific external resource occurs if and only if the external resource's connector 
instance capabilities permit.
Propagation will be tried on an external resource for each provisioning operation involving users or roles assigned 
to that resource.

===== Configuration
Connectors::
Connector instances can be configured to create, update and delete operations.
Propagation tasks::
When propagation tasks are created, their propagation mode will be set according to the mode of the external resource.
Operation::
When tasks are executed, the execution status will be set to SUCCESS or FAILURE, based on the actual propagation result.