//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
===== Configuration command
This command works with <<configuration-parameters,configuration parameters>>.

[discrete]
====== Help message
[source,bash]
----
Usage: configuration [options]
  Options:
    --help 
    --get 
    --read 
       Syntax: --read {CONF-NAME} {CONF-NAME} [...] 
    --update 
       Syntax: --update {CONF-NAME}={CONF-VALUE} {CONF-NAME}={CONF-VALUE} [...]
    --delete 
       Syntax: --delete {CONF-NAME} {CONF-NAME} [...]
    --export 
       Syntax: --export {WHERE-DIR}

----

[discrete]
====== Options

--get::
This get option shows a table with the Syncope configuration.
--read::
The option to read the value of specified configuration attributes.
--update::
The option to update a value of specified configuration attributes.
--delete::
The option to delete specified configuration attributes.
--export::
The option to export the Syncope configuration to a specified directory.
