//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

===== Entitlement command
This command works with <<entitlements,entitlements>>.

[discrete]
====== Help message
[source,bash]
----
Usage: entitlement [options]
  Options:
    --help 
    --list
    --list-role
       Syntax: --list-role {ENTITLEMENT-NAME}
    --read-by-username
       Syntax: --read-by-username {USERNAME}
    --read-by-userkey
       Syntax: --read-by-userkey {USER-KEY}
    --search-by-role
       Syntax: --search-by-role {ROLE-KEY}
----

[discrete]
====== Options

--list::
Running the command with this option you will see the list of the entitlements.
--list-role::
Running the command with this option you will see the list of the roles with a certain entitlement.
--read-by-username::
The option to read the entitlements of the username passed as input.
--read-by-userkey::
The option to read the entitlements of the user key passed as input.
--search-by-role::
The option to read the entitlements of a certain role.
