//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

==== Initial Setup
The installation process creates `cli.properties`, which contains all the required information to invoke the Apache 
Syncope REST API services.
The file content looks like the following:

[source]
syncope.rest.services=http://localhost:9080/syncope/rest
syncope.admin.user=admin
syncope.admin.password=QePSFVTnzwQowM4ohhaUYcE6aW47MVZ/

where:

syncope.rest.services::
    the base URL where the Apache Syncope REST API services are listening;
syncope.admin.user::
    the username which will be used to invoke the Syncope APIs;
syncope.admin.password::
    the password for the admin user configured above.

As shown above, the password value is encrypted for security reasons.

[discrete]
====== Help message
[source,bash]
----
Usage: install [options]
  Options:
    --help 
    --setup
    --setup-debug
----

===== Run the installation
After the zip file is unzipped you can start with CLI client using the syncopeadm file.
If you tried to run a CLI command before the installation process, the script returns
[source]
--
 - Error: It seems you need to first setup the CLI client. Run install --setup.
--

So, as suggested, you have to run the install command to use the CLI:
[source]
--
$ ./syncopeadm.sh install --setup
--

A successful result will be:
[source,bash,subs="verbatim,attributes"]
----

You are running: install --setup 

###############################################
#                                             #
# Welcome to Syncope CLI installation process #
#                                             #
###############################################

Path to config files of Syncope CLI client will be: ./
- File system permission checked

Syncope server schema [http/https]: http
Syncope server hostname [e.g. localhost]: localhost
Syncope server port [e.g. 8080]: 9080
Syncope server rest context [e.g. /syncope/rest/]: /syncope/rest
Syncope admin user: admin
Syncope admin password: password
Installation parameters checked on Syncope core version: {docVersion}

###############################################
#                                             #
#           Installation successful           #
#     now you can use Syncope CLI client      #
#                                             #
###############################################

----

During the installation you have to provide:

Syncope server schema::
    the http protocol used by the Apache Syncope core, it will be http or https;
Syncope server hostname::
    the hostname where the core is deployed;
Syncope server port::
    the port where the services are listening;
Syncope server rest context::
    the context where the rest services are deployed (/syncope/rest is the default);
Syncope admin user::
    the user with the permission to call the Syncope APIs;
Syncope admin password::
    the user password.

===== Installation error
Various error messages are possible on installation. Here are some sample error messages:

* Syncope unreachable (or wrong address):

[source]
--

Provided address :http://localhost:9080/syncope/rest

###############################################
#                                             #
#       Provided address is unreachable!      #
#         Check it and if it is wrong         #
#        START the installation AGAIN!        #
#                                             #
###############################################

--

* Authentication failed:

[source]
--

###############################################
#                                             #
#   Username or password provided are wrong   #
#        START the installation AGAIN!        #
#                                             #
###############################################

--

As the message suggests you have to start the installation again when this error occurrs.


===== Debug installation
To work with the debug environment provided by Syncope we added a particular installation option for it.
It enough to run the script with the --setup-debug option
[source]
--
$ ./syncopeadm.sh install --setup-debug
--
[source,bash,subs="verbatim,attributes"]
----

You are running: install --setup-debug 

###############################################
#                                             #
# Welcome to Syncope CLI installation process #
#                                             #
###############################################

Path to config files of Syncope CLI client will be: ./
- File system permission checked

Installation parameters checked on Syncope core version: {docVersion}

###############################################
#                                             #
#           Installation successful           #
#     now you can use Syncope CLI client      #
#                                             #
###############################################

----

