//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
===== Report command
This command works with <<reports,reports>>.

[discrete]
====== Help message
[source,bash]
----
Usage: report [options]
  Options:
    --help 
    --details
    --list 
    --list-jobs 
    --read 
       Syntax: --read {REPORT-KEY} {REPORT-KEY} [...] 
    --delete 
       Syntax: --delete {REPORT-KEY} {REPORT-KEY} [...]
    --execute 
       Syntax: --execute {REPORT-KEY} 
    --read-execution 
       Syntax: --read-execution {EXECUTION-KEY} {EXECUTION-KEY} [...]
    --delete-execution 
       Syntax: --delete-execution {EXECUTION-KEY} {EXECUTION-KEY} [...]
    --export-execution-result 
       Syntax: --export-execution-result {EXECUTION-KEY} {EXECUTION-KEY} [...] {FORMAT}
          Format: CSV / HTML / PDF / XML / RTF
----

[discrete]
====== Options

--details::
This option shows a table with some details about the reports and their executions.
--list::
Running the command with this option you will see the list of configured reports.
--list-jobs::
Running the command with this option you will see the list of the report executions.
--read::
The option to read all the information of a specified report.
--read-execution::
The option to read all the information of a specified report execution.
--delete::
The option to delete a specified report.
--delete-execution::
The option to delete a specified report execution.
--execute::
The option to run a report.
--export-execution-result::
The option to export an execution in a certain format to see the results.
