//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
===== Schema command
This command works with <<schema,schemas>>.

[discrete]
====== Help message
[source,bash]
----
Usage: schema [options]
  Options:
    --help 
    --details 
    --list-all
    --list-plain
    --list-derived
    --list-virtual
    --read {SCHEMA-TYPE} {SCHEMA-KEY}
        Schema type: PLAIN / DERIVED / VIRTUAL
    --delete {SCHEMA-TYPE} {SCHEMA-KEY}
        Schema type: PLAIN / DERIVED / VIRTUAL
----

[discrete]
====== Options

--details::
This option shows a table with some details about the schemas and their categories.
--list-all::
Running the command with this option you will see the list of all (PLAIN, DERIVED, VIRTUAL) schemas configured.
--list-plain::
Running the command with this option you will see the list of the plain schemas available in Syncope.
--list-derived::
Running the command with this option you will see the list of the derived schemas available in Syncope with 
their expressions.
--list-virtual::
Running the command with this option you will see the list of the virtual schemas available in Syncope.
--read::
The option to read all the information of a specified schema.
--delete::
The option to delete a specified schema.
