//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
===== Task command
This command works with <<tasks,tasks>>.

[discrete]
====== Help message
[source,bash]
----
Usage: task [options]
  Options:
    --help 
    --details
    --list
       Syntax: --list {TASK-TYPE} 
          Task type: NOTIFICATION / PROPAGATION / PUSH / SCHEDULED / PULL
    --list-running-jobs
    --list-scheduled-jobs
    --read 
       Syntax: --read {TASK-KEY} {TASK-KEY} [...]
    --read-execution 
       Syntax: --read-execution {TASK-EXEC-KEY} {TASK-EXEC-KEY} [...]
    --delete 
       Syntax: --delete {TASK-KEY} {TASK-KEY} [...]
    --delete-execution 
       Syntax: --delete-execution {TASK-EXEC-KEY} {TASK-EXEC-KEY} [...]
    --execute 
       Syntax: --execute {TASK-KEY} {DRY-RUN}
          Dry run: true / false
----

[discrete]
====== Options

--details::
This option shows a table with some details about tasks and jobs.
--list::
Running the command with this option you will see the list of selected tasks type with their information.
--list-scheduled-jobs::
Running the command with this option you will see the list of the actual scheduled jobs.
--list-running-jobs::
Running the command with this option you will see the list of the actual running jobs.
--read::
The option to read all the information of a task.
--read-execution::
The option to read all the information of the specified task execution(s).
--delete::
The option to delete specified tasks.
--delete-execution::
The option to delete the specified task execution(s).
--execute::
The option to execute the specified task.
