//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
=== Attribute Repositories

Attribute Repositories allow to enrich the profile of an user authenticated by <<web-access,WA>>, in the context of a
certain <<policies-attribute-release,Attribute Release Policy>>.

Some attribute repositories are provided:

* https://apereo.github.io/cas/7.2.x/integration/Attribute-Resolution-JDBC.html[Database^]
* https://apereo.github.io/cas/7.2.x/integration/Attribute-Resolution-LDAP.html[LDAP^]
* https://apereo.github.io/cas/7.2.x/integration/Attribute-Resolution-Stub.html[Stub^]
* https://apereo.github.io/cas/7.2.x/integration/Attribute-Resolution-Syncope.html[Syncope^]
* https://apereo.github.io/cas/7.2.x/integration/Attribute-Resolution-AzureAD.html[Azure Active Directory^]
* https://apereo.github.io/cas/7.2.x/integration/Attribute-Resolution-Okta.html[Okta^]

[TIP]
====
Custom authentication modules can be provided by implementing the
ifeval::["{snapshotOrRelease}" == "release"]
https://github.com/apache/syncope/blob/syncope-{docVersion}/common/am/lib/src/main/java/org/apache/syncope/common/lib/attr/AttrRepoConf.java[AttrRepoConf^]
endif::[]
ifeval::["{snapshotOrRelease}" == "snapshot"]
https://github.com/apache/syncope/blob/master/common/am/lib/src/main/java/org/apache/syncope/common/lib/attr/AttrRepoConf.java[AttrRepoConf^]
endif::[]
interface and extending appropriately the
ifeval::["{snapshotOrRelease}" == "release"]
https://github.com/apache/syncope/blob/syncope-{docVersion}/wa/bootstrap/src/main/java/org/apache/syncope/wa/bootstrap/WAPropertySourceLocator.java[WAPropertySourceLocator^]
endif::[]
ifeval::["{snapshotOrRelease}" == "snapshot"]
https://github.com/apache/syncope/blob/master/wa/bootstrap/src/main/java/org/apache/syncope/wa/bootstrap/WAPropertySourceLocator.java[WAPropertySourceLocator^]
endif::[]
class.
====

[NOTE]
Attribute Repositories are dynamically translated into 
https://apereo.github.io/cas/7.2.x/integration/Attribute-Resolution.html[CAS Attribute Resolution^] configuration.
