//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
== Concepts

include::usersgroupsandanyobjects.adoc[]

include::typemanagement.adoc[]

=== External Resources

==== Mapping

=== Realms

=== Roles

=== Domains

include::provisioning/provisioning.adoc[]

=== Policies

==== Account

==== Password

[[policies-pull]]
==== Pull

[[policies-push]]
==== Push

=== Workflow and Approval

=== Notifications

=== Tasks

[[tasks-propagation]]
==== Propagation

[[tasks-pull]]
==== Pull

[[tasks-push]]
==== Push

[[tasks-notification]]
==== Notification

[[tasks-generic]]
==== Generic

=== Reports

=== Audit

=== Delegated Administration

The idea is that any user U assigned to a role R, which provides entitlements E~1~...E~n~ for realms Re~1~...Re~k~ can 
exercise E~i~ on entities (users or groups, depending on the type of E~i~) under any Re~j~ or related sub-realms.

About group membership and any relationships:

* User U can be member of group G either if U and G are in the same realm, or G is in one of super-realms of the realm 
of U
* Any object A~1~ can be in relationship with any object A~2~ either if A~1~ and A~2~ are in the same realm, or A~2~ is
in one of super-realms of the realm of A~1~

The rationale behind such conditions is to allow the definition of common groups and any objects (to enter in 
relationship with) at the topmost position in the realm tree, so that they can be shared by various realm sub-trees.

[discrete]
==== Example

Let's suppose that we want to implement the following scenario:

****
Administrator A can create users under realm R~5~ but not under realm R~7~, administrator B can update users under 
realm R~6~ and R~8~, administrator C can update groups under realm R~8~.
****

As default, Syncope will have defined the following entitlements, among others:

* `USER_CREATE`
* `USER_UPDATE`
* `GROUP_UPDATE`

Here it follows how entitlements should be assigned (via roles) to administrators in order to implement the scenario 
above:

* A: `USER_CREATE` on R~5~
* B: `USER_UPDATE` on R~6~ and R~8~
* C: `GROUP_UPDATE` on R~8~
