//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
=== Implementations

It is possible to provide implementations suitable for <<customization-core,customization>> as:

. Java classes
. http://www.groovy-lang.org/[Apache Groovy^] classes

While the former shows some advantages about execution performance, the latter is extremely useful as it allows for
runtime updates, freeing from the hassle to redeploy when something needs to be changed.

[WARNING]
.With great power comes great responsibility
====
Customizing and extending the Core behavior by uploading a Groovy class via REST adds further flexibility to the
platform, allows to speed up the development cycle and can be used as Swiss army knife for maintenance and
administration.

Please beware that granting the permission to manage Implementations to non-admin users can result in security threat,
as there is virtually no limitation in what the Groovy code has access to.
====
