//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
=== Password Management

Password Management allows handling the password update flow of a user authenticated via <<web-access, WA>>
according to rules defined by a single configured password management module (only one module can be active at a time).

Some password management modules are provided:

* https://apereo.github.io/cas/7.2.x/password_management/Password-Management-LDAP.html[LDAP^]
* https://apereo.github.io/cas/7.2.x/password_management/Password-Management-JDBC.html[JDBC^]
* https://apereo.github.io/cas/7.2.x/password_management/Password-Management-REST.html[REST^]
* https://apereo.github.io/cas/7.2.x/password_management/Password-Management-ApacheSyncope.html[Syncope^]

[TIP]
====
Custom password management modules can be provided by implementing the
ifeval::["{snapshotOrRelease}" == "release"]
https://github.com/apache/syncope/blob/syncope-{docVersion}/common/am/lib/src/main/java/org/apache/syncope/common/lib/password/PasswordManagementConf.java[PasswordManagementConf^]
endif::[]
ifeval::["{snapshotOrRelease}" == "snapshot"]
https://github.com/apache/syncope/blob/master/common/am/lib/src/main/java/org/apache/syncope/common/lib/password/PasswordManagementConf.java[PasswordManagementConf^]
endif::[]
interface and extending appropriately the
ifeval::["{snapshotOrRelease}" == "release"]
https://github.com/apache/syncope/blob/syncope-{docVersion}/wa/bootstrap/src/main/java/org/apache/syncope/wa/bootstrap/WAPropertySourceLocator.java[WAPropertySourceLocator^]
endif::[]
ifeval::["{snapshotOrRelease}" == "snapshot"]
https://github.com/apache/syncope/blob/master/wa/bootstrap/src/main/java/org/apache/syncope/wa/bootstrap/WAPropertySourceLocator.java[WAPropertySourceLocator^]
endif::[]
class.
====

[NOTE]
Password Management is dynamically translated into
https://apereo.github.io/cas/7.2.x/password_management/Password-Management.html[CAS Password Management^] configuration.
