//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

==== Connector command
The connector command serves to retrieve information about the connector configuration in Apache Syncope.

===== Help message
[source,bash]
----
Usage: connector [options]
  Options:
    --help 
    --details 
    --list 
    --list-bundles 
    --list-configuration-properties
       Syntax: --list-configuration-properties {CONNECTOR-ID} {CONNECTOR-ID} [...]
    --read 
       Syntax: --read {CONNECTOR-ID} {CONNECTOR-ID} [...]
    --delete 
       Syntax: --delete {CONNECTOR-ID} {CONNECTOR-ID} [...]
----

===== Options

--details::
This option shows a table with some details about connectors and bundles.
--list::
Running the command with this option you will see the list of connectors with their configuration.
--list-bundles::
Running the command with this option you will see the list of the bundles available in Syncope.
--list-configuration-properties::
This option lists the configuration of specified connectors.
--read::
The option to read all the information of specified connectors.
--delete::
The option to delete a specified connector.
