//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

==== Group command
The group command retrieves information about the configured groups.

===== Help message
[source,bash]
----
Usage: group [options]
  Options:
    --help 
    --details 
    --list 
    --read 
       Syntax: --read {GROUP-ID} {GROUP-ID} [...]
    --read-attr-by-schema-type {GROUP-ID} {SCHEMA-TYPE}
       Schema type: PLAIN / DERIVED / VIRTUAL
    --read-attr-by-schema {GROUP-ID} {SCHEMA-TYPE} {SCHEMA-NAME}
       Schema type: PLAIN / DERIVED / VIRTUAL
    --delete 
       Syntax: --delete {GROUP-ID} {GROUP-ID} [...]
----

===== Options

--details::
This option shows a table with the amount of available groups and some additional information.
--list::
Running the command with this option you will see the list of the groups.
--read::
The option to read the group passed as input.
--read-attr-by-schema-type::
The option to read the specified attribute type of the group passed as input.
--read-attr-by-schema::
The option to read the specified attribute name of the group passed as input.
--delete::
The option to delete a specified group.
