//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

== Moving Forward

Once you have obtained a working installation of Apache Syncope using one of the methods reported above, you should
consider  reading the
ifeval::["{backend}" == "html5"]
https://syncope.apache.org/docs/4.1/reference-guide.html[Apache Syncope Reference Guide.]
endif::[]
ifeval::["{backend}" == "pdf"]
https://syncope.apache.org/docs/4.1/reference-guide.pdf[Apache Syncope Reference Guide.]
endif::[]
to understand how to configure, extend, customize and deploy your new Apache Syncope project.

Before deploying your Apache Syncope installation into production, it is [.underline]#essential to ensure that the
default values for various security properties have been changed to values specific to your deployment#. 

The following values **must be changed** from the defaults in the `core.properties` file:

* `security.adminPassword`
* `security.anonymousKey`
* `security.aesSecretKey`
* `security.jwsKey`

Note that if you installed Syncope using the maven archetype method, then you will have already supplied custom values
for `security.aesSecretKey`, `security.anonymousKey` and `security.jwsKey`.

See the https://syncope.apache.org/docs/4.1/reference-guide.html#security[security configuration section] for more details.
