/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.apache.syncope.netbeans.plugin.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.apache.syncope.common.lib.to.MailTemplateTO;
import org.apache.syncope.common.lib.to.ReportTemplateTO;
import org.apache.syncope.netbeans.plugin.connector.ResourceConnector;
import org.apache.syncope.netbeans.plugin.constants.PluginConstants;
import org.apache.syncope.netbeans.plugin.service.MailTemplateManagerService;
import org.apache.syncope.netbeans.plugin.service.ReportTemplateManagerService;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Exceptions;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.apache.syncope.netbeans.plugin//ResourceExplorer//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "ResourceExplorerTopComponent",
        iconBase = "images/syncope.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "explorer", openAtStartup = false)
@ActionID(category = "Window", id = "org.apache.syncope.netbeans.plugin.ResourceExplorerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ResourceExplorerAction",
        preferredID = "ResourceExplorerTopComponent"
)
@Messages({
    "CTL_ResourceExplorerAction=Apache Syncope",
    "CTL_ResourceExplorerTopComponent=Apache Syncope",
    "HINT_ResourceExplorerTopComponent=This is a Apache Syncope window"
})
public final class ResourceExplorerTopComponent extends TopComponent {

    private DefaultTreeModel treeModel;
    private DefaultMutableTreeNode root;
    private DefaultMutableTreeNode mailTemplates;
    private DefaultMutableTreeNode reportXslts;
    private MailTemplateManagerService mailTemplateManagerService;
    private ReportTemplateManagerService reportTemplateManagerService;
    private Map<String, MailTemplateTopComponent> mailTemplateComponents;
    private Map<String, ReportXsltsTopComponent> reportXsltsComponents;

    public ResourceExplorerTopComponent() {

        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Exceptions.printStackTrace(ex);
        }

        initComponents();
        setName(Bundle.CTL_ResourceExplorerTopComponent());
        setToolTipText(Bundle.HINT_ResourceExplorerTopComponent());

        mailTemplateManagerService = ResourceConnector.getMailTemplateManagerService();
        reportTemplateManagerService = ResourceConnector.getReportTemplateManagerService();
        treeModel = (DefaultTreeModel) resourceExplorerTree.getModel();
        root = (DefaultMutableTreeNode) treeModel.getRoot();
        mailTemplates = new DefaultMutableTreeNode(PluginConstants.MAIL_TEMPLTAE_CONSTANT);
        reportXslts = new DefaultMutableTreeNode(PluginConstants.REPORT_XSLTS_CONSTANT);
        mailTemplateComponents = new HashMap<String, MailTemplateTopComponent>();
        reportXsltsComponents = new HashMap<String, ReportXsltsTopComponent>();

        root.add(mailTemplates);
        root.add(reportXslts);
        treeModel.reload();

        addMailTemplates();
        addReportXslts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resourceExplorerTree = new javax.swing.JTree();

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        resourceExplorerTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        resourceExplorerTree.setRootVisible(false);
        resourceExplorerTree.setScrollsOnExpand(true);
        resourceExplorerTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resourceExplorerTreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(resourceExplorerTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resourceExplorerTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resourceExplorerTreeMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() == 2) {
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) resourceExplorerTree.getLastSelectedPathComponent();
            DefaultMutableTreeNode parentNode = (DefaultMutableTreeNode) selectedNode.getParent();
            if (selectedNode.isLeaf()) {
                String name = (String) selectedNode.getUserObject();
                if (parentNode.getUserObject().equals(PluginConstants.MAIL_TEMPLTAE_CONSTANT)) {
                    MailTemplateTopComponent viewComponent = mailTemplateComponents.get(name);
                    if (viewComponent == null) {
                        viewComponent = new MailTemplateTopComponent(name);
                        mailTemplateComponents.put(name, viewComponent);
                    }
                    viewComponent.openAtTabPosition(0);
                    viewComponent.requestActive();
                } else {
                    ReportXsltsTopComponent viewComponent = reportXsltsComponents.get(name);
                    if (viewComponent == null) {
                        viewComponent = new ReportXsltsTopComponent(name);
                        reportXsltsComponents.put(name, viewComponent);
                    }
                    viewComponent.openAtTabPosition(0);
                    viewComponent.requestActive();
                }
            }
        } else if (evt.getButton() == MouseEvent.BUTTON3 && evt.getClickCount() == 1) {
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) resourceExplorerTree.getLastSelectedPathComponent();
            String selectedNodeName = (String) selectedNode.getUserObject();
            if (selectedNode.isLeaf()) {
                leafRightClickAction(evt,selectedNode);
            } else if (selectedNodeName.equals(PluginConstants.MAIL_TEMPLTAE_CONSTANT)) {
                folderRightClickAction(evt,mailTemplates);
            } else if (selectedNodeName.equals(PluginConstants.REPORT_XSLTS_CONSTANT)) {
                folderRightClickAction(evt, reportXslts);
            }
        }
    }//GEN-LAST:event_resourceExplorerTreeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree resourceExplorerTree;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    private void addMailTemplates() {
        List<MailTemplateTO> mailTemplates = mailTemplateManagerService.list();
        for (MailTemplateTO mailTemplate : mailTemplates) {
            this.mailTemplates.add(new DefaultMutableTreeNode(mailTemplate.getKey()));
        }
        treeModel.reload();
    }

    private void addReportXslts() {
        List<ReportTemplateTO> reportTemplates = reportTemplateManagerService.list();
        for (ReportTemplateTO reportTemplate : reportTemplates) {
            reportXslts.add(new DefaultMutableTreeNode(reportTemplate.getKey()));
        }
        treeModel.reload();
    }
    
    private void folderRightClickAction(final MouseEvent evt,final DefaultMutableTreeNode node){
        JPopupMenu menu = new JPopupMenu();
        JMenuItem addItem = new JMenuItem("New");
        menu.add(addItem);
        
        addItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String name = JOptionPane.showInputDialog("Enter Name");
                boolean added;
                if(node.getUserObject().equals(PluginConstants.MAIL_TEMPLTAE_CONSTANT)){
                    MailTemplateTO mailTemplate = new MailTemplateTO();
                    mailTemplate.setKey(name);
                    added = mailTemplateManagerService.create(mailTemplate);
                    MailTemplateTopComponent component = new MailTemplateTopComponent(name);
                    mailTemplateComponents.put(name, component);
                    component.openAtTabPosition(0);
                    component.requestActive();
                }else{
                    ReportTemplateTO reportTemplate = new ReportTemplateTO();
                    reportTemplate.setKey(name);
                    added = reportTemplateManagerService.create(reportTemplate);
                    ReportXsltsTopComponent component = new ReportXsltsTopComponent(name);
                    reportXsltsComponents.put(name, component);
                    component.openAtTabPosition(0);
                    component.requestActive();
                }
                
                if(added){
                    node.add(new DefaultMutableTreeNode(name));
                    treeModel.reload(node);
                }else{
                    JOptionPane.showMessageDialog(null, "Error while creating "
                            + "new element", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        menu.show(evt.getComponent(), evt.getX(), evt.getY());
    }
    
    private void leafRightClickAction(final MouseEvent evt , final DefaultMutableTreeNode node){
        JPopupMenu menu = new JPopupMenu();
        JMenuItem deleteItem = new JMenuItem("Delete");
        menu.add(deleteItem);
        
        deleteItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int result = JOptionPane.showConfirmDialog(null, "Do you want to delete ?");
                if (result == JOptionPane.OK_OPTION) {
                    DefaultMutableTreeNode parent = (DefaultMutableTreeNode) node.getParent();
                    String name = (String) node.getUserObject();
                    boolean deleted;
                    if (parent.getUserObject().equals(PluginConstants.MAIL_TEMPLTAE_CONSTANT)) {
                        deleted = mailTemplateManagerService.delete((String) node.getUserObject());
                        MailTemplateTopComponent component = mailTemplateComponents.get(name);
                        component.close();
                        mailTemplateComponents.remove(name);
                    } else {
                        deleted = reportTemplateManagerService.delete((String) node.getUserObject());
                        ReportXsltsTopComponent component = reportXsltsComponents.get(name);
                        component.close();
                        reportXsltsComponents.remove(name);
                    }
                    if (deleted) {
                        node.removeFromParent();
                        treeModel.reload(parent);
                    } else {
                        JOptionPane.showMessageDialog(null, "Error while deleting "
                                + "new element", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
        menu.show(evt.getComponent(), evt.getX(), evt.getY());
    }
}
